version: 2

references:
  defaults: &defaults
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/react-oneteam
  restore_yarn_cache: &restore_yarn_cache
    name: Restoring Cache - yarn
    keys:
      - comuque-frontend-yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - comuque-frontend-yarn-v1-{{ .Branch }}-
  save_yarn_cache: &save_yarn_cache
    name: Saving Cache - yarn
    key: comuque-frontend-yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - ./node_modules
  system_information: &system_information
    name: System information
    command: |
      echo "Node.js $(node -v)"
      echo "npm $(npm -v)"
      echo "Yarn v$(yarn --version)"

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: *system_information
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: ESLint
          command: npm run lint
      - run:
          name: Tests and Coverage report
          command: |
            npm run test:coverage && ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov
      - save_cache: *save_yarn_cache
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ~/.npmrc
      - run:
          name: Publish package to npm and tagging by Git
          command: /bin/bash .circleci/publish-and-tagging.sh

workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
